run:
  tests: false
issues:
  # exclude-use-default: false
  exclude: 
    - ST1000 # stylelint for comment on top of at least one file in a package 
linters:
  enable-all: true
  disable:
    - tagliatelle
